/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proj2ui.LoginUI;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.ButtonType;
import proj2.BLL.UtilizadorJpaController;
import proj2.DAL.Utilizador;
import proj2ui.Alerta;
import proj2ui.Home;
import proj2ui.MainFrame;
import javafx.embed.swing.JFXPanel;


/**
 *
 * @author nunop
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
     private MainFrame parentFrame = null;
    public Login(MainFrame parentFrame) {
        initComponents();
        this.parentFrame = parentFrame;
        this.parentFrame.getJMenuBar().setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        showpassCheck = new javax.swing.JCheckBox();
        passwordText = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(884, 525));
        setPreferredSize(new java.awt.Dimension(884, 525));

        LoginLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LoginLabel.setText("Login");

        emailLabel.setText("Email");
        emailLabel.setMaximumSize(new java.awt.Dimension(46, 14));
        emailLabel.setMinimumSize(new java.awt.Dimension(46, 14));
        emailLabel.setPreferredSize(new java.awt.Dimension(46, 14));

        passwordLabel.setText("Password");

        emailText.setMaximumSize(new java.awt.Dimension(6, 20));

        loginButton.setBackground(new java.awt.Color(153, 153, 255));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        resetButton.setBackground(new java.awt.Color(153, 153, 255));
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        showpassCheck.setText("Mostrar password");
        showpassCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassCheckActionPerformed(evt);
            }
        });

        passwordText.setMaximumSize(new java.awt.Dimension(6, 20));
        passwordText.setPreferredSize(new java.awt.Dimension(6, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(passwordLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(loginButton)
                                    .addGap(65, 65, 65)
                                    .addComponent(resetButton))
                                .addComponent(showpassCheck)
                                .addComponent(LoginLabel)
                                .addComponent(emailLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(emailText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(350, 350, 350))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(LoginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showpassCheck)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton)
                    .addComponent(resetButton))
                .addContainerGap(203, Short.MAX_VALUE))
        );

        LoginLabel.getAccessibleContext().setAccessibleName("login");
        emailLabel.getAccessibleContext().setAccessibleName("emailLabel");
        passwordLabel.getAccessibleContext().setAccessibleName("passwordLabel");
        emailText.getAccessibleContext().setAccessibleName("emailText");
        loginButton.getAccessibleContext().setAccessibleName("LoginBT");
        resetButton.getAccessibleContext().setAccessibleName("ResetBT");
        showpassCheck.getAccessibleContext().setAccessibleName("showpassCheck");
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        final JFXPanel fxPanel = new JFXPanel();
        String email;
        String pass;
        Integer rt;
        email = emailText.getText();
        pass = passwordText.getText();
        rt = UtilizadorJpaController.login(email,pass);
        Utilizador user = UtilizadorJpaController.readUser(rt);
        if(rt!=null && user.getTipoutil()==3){
            /*Alert alert = new Alert(AlertType.ERROR, 
                        "File already exists. Do you want to override?", 
                        ButtonType.OK);
            alert.showAndWait();*/
        }else if(rt!=null){
            Home home = new Home(this.parentFrame,user);
            this.parentFrame.setPainelVisivel(home); 
            this.parentFrame.setContentPane(this.parentFrame.getPainelVisivel());
            this.parentFrame.setVisible(true);
            this.parentFrame.repaint();
        }
        
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void showpassCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassCheckActionPerformed
           // TODO add your handling code here:
           if(showpassCheck.isSelected()){
               passwordText.setEchoChar((char)0);
           }else{
               passwordText.setEchoChar('*');
           }
    }//GEN-LAST:event_showpassCheckActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        emailText.setText("");
        passwordText.setText("");
        if(showpassCheck.isSelected())
            showpassCheck.setSelected(false);
    }//GEN-LAST:event_resetButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailText;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JButton resetButton;
    private javax.swing.JCheckBox showpassCheck;
    // End of variables declaration//GEN-END:variables
}
