/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proj2ui.Admin;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import proj2.BLL.CategoriaJpaController;
import proj2.BLL.UtilizadorJpaController;
import proj2.DAL.Categoria;
import proj2.DAL.Utilizador;
import proj2ui.MainFrame;

/**
 *
 * @author miguel
 */
public class ListarUtilizador extends javax.swing.JPanel {
    private MainFrame parentFrame = null;
    /**
     * Creates new form ListarClientesUI
     */
    public ListarUtilizador(MainFrame parentFrame) {
        initComponents();
        this.parentFrame = parentFrame;
        List<Utilizador> listaUtilizador = null;
        //DefaultTableModel tmodel = new DefaultTableModel();
        DefaultTableModel tmodel = (DefaultTableModel) jTable1.getModel();

        listaUtilizador = UtilizadorJpaController.readByTipoUtil((short) (3));
    

        for (Utilizador cli : listaUtilizador) {
            String[] linhaTabela = new String[10];
            linhaTabela[0] = cli.getIdUtilizador().toString();
            if (cli.getEstado() == 0) {
                linhaTabela[1] = "Ativo";
            } else {
                linhaTabela[1] = "Desativo";
            }
            linhaTabela[2] = cli.getEmail();
            linhaTabela[3] = cli.getNif();
            linhaTabela[4] = cli.getNome();
            linhaTabela[5] = cli.getMorada();
            linhaTabela[6] = cli.getLocalidade();
            linhaTabela[7] = cli.getCodPostal();
            linhaTabela[8] = cli.getTelefone();
           
            tmodel.addRow(linhaTabela);
            //System.out.println(linhaTabela[0]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(884, 525));
        setMinimumSize(new java.awt.Dimension(884, 525));
        setPreferredSize(new java.awt.Dimension(884, 525));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Lista de Clientes");
        jLabel1.setMaximumSize(new java.awt.Dimension(143, 22));
        jLabel1.setMinimumSize(new java.awt.Dimension(143, 22));
        jLabel1.setPreferredSize(new java.awt.Dimension(143, 22));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {  },
            new String [] {
                "ID Utilizador","Estado","Email","NIF", "Nome", "Morada","Localidade", "Cod.Postal","Telefone"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int linha = this.jTable1.getSelectedRow();
        
        int idEntidade = Integer.parseInt((String) ((DefaultTableModel) this.jTable1.getModel()).getValueAt(linha, 0));

        Utilizador user = UtilizadorJpaController.readUser(idEntidade);
        
        System.out.print(user);
        VerUtilizadores ver = new VerUtilizadores(user);
        this.parentFrame.setPainelVisivel(ver);       
        this.parentFrame.setContentPane(this.parentFrame.getPainelVisivel());
        this.parentFrame.setVisible(true);
        this.parentFrame.repaint();
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
