/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proj2ui.Admin;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import proj2.BLL.CategoriaJpaController;
import proj2.BLL.UtilizadorJpaController;
import proj2.DAL.Categoria;
import proj2.DAL.Utilizador;

/**
 *
 * @author nunop
 */
public class VerUtilizadores extends javax.swing.JPanel {

    /**
     * Creates new form Criar
     */
    int id;
    public VerUtilizadores(Utilizador user) {
        initComponents();
        int estado =user.getEstado();
        if(estado==0){
            jCheckBox1.setSelected(true);
        }else if(estado ==1){
            jCheckBox1.setSelected(false);
        }
        id=user.getIdUtilizador();
        if(user.getTipoutil()==2){
        Categoria cat = CategoriaJpaController.readByIdCategoria(user.getIdCategoria());
        jLabel1.setText("Entidade nrº "+id);
        nomeText.setText(user.getNome());
        moradaText.setText(user.getMorada());
        localText.setText(user.getLocalidade());
        postalText.setText(user.getCodPostal());
        emailText.setText(user.getEmail());
        nifText.setText(user.getNif());        
        telefoneText.setText(user.getTelefone());
        catText.setText(cat.getNome());
        descText.setText(user.getDescricao());  
        }else if(user.getTipoutil()==3){
        jLabel1.setText("Utilizador nrº "+id);
        nomeText.setText(user.getNome());
        moradaText.setText(user.getMorada());
        localText.setText(user.getLocalidade());
        postalText.setText(user.getCodPostal());
        emailText.setText(user.getEmail());
        nifText.setText(user.getNif());        
        telefoneText.setText(user.getTelefone());
        catLabel.setVisible(false);
        descLabel.setVisible(false);
        catText.setVisible(false);
        descText.setVisible(false);
        }else if(user.getTipoutil()==1){
        jLabel1.setText("Admin nrº "+id);
        nomeText.setText(user.getNome());
        moradaLabel.setText("Email: ");
        moradaText.setText(user.getEmail());
        localLabel.setText("NIF: ");
        localText.setText(user.getNif());
        codLabel.setText("Telefone: ");
        postalText.setText(user.getTelefone());
        emailText.setVisible(false);
        nifText.setVisible(false);    
        telefoneText.setVisible(false);
        catLabel.setVisible(false);
        descLabel.setVisible(false);
        catText.setVisible(false);
        descText.setVisible(false);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        moradaLabel = new javax.swing.JLabel();
        localLabel = new javax.swing.JLabel();
        codLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        descLabel = new javax.swing.JLabel();
        catLabel = new javax.swing.JLabel();
        feedbackMessage = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        descText = new javax.swing.JLabel();
        nomeText = new javax.swing.JLabel();
        moradaText = new javax.swing.JLabel();
        localText = new javax.swing.JLabel();
        nifText = new javax.swing.JLabel();
        emailText = new javax.swing.JLabel();
        catText = new javax.swing.JLabel();
        postalText = new javax.swing.JLabel();
        telefoneText = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(884, 525));
        setMinimumSize(new java.awt.Dimension(884, 525));
        setPreferredSize(new java.awt.Dimension(884, 525));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Entidade nrº");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome: ");

        moradaLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        moradaLabel.setText("Morada: ");

        localLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        localLabel.setText("Localidade: ");

        codLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codLabel.setText("Cod.Postal: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Email: ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("NIF:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Telefone:");

        descLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descLabel.setText("Descrição: ");

        catLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        catLabel.setText("Categoria: ");

        feedbackMessage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jCheckBox1.setText("Ativo");
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(feedbackMessage)))
                .addGap(0, 756, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(localLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(localText)))
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(codLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(postalText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telefoneText))))
                    .addComponent(jCheckBox1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(descLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descText))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(catLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(catText))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nifText))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(moradaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moradaText))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeText)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(411, 411, 411)
                .addComponent(feedbackMessage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeText))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moradaLabel)
                    .addComponent(moradaText))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codLabel)
                    .addComponent(localLabel)
                    .addComponent(localText)
                    .addComponent(postalText))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nifText))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(emailText)
                    .addComponent(telefoneText))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catLabel)
                    .addComponent(catText))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descLabel)
                    .addComponent(descText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox1)
                .addGap(95, 95, 95))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
            UtilizadorJpaController.changeEstado(id, 0);
            System.out.print("done 0");
        }else{
            UtilizadorJpaController.changeEstado(id, 1);
            System.out.print("done 1");
        }
    }//GEN-LAST:event_jCheckBox1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel catLabel;
    private javax.swing.JLabel catText;
    private javax.swing.JLabel codLabel;
    private javax.swing.JLabel descLabel;
    private javax.swing.JLabel descText;
    private javax.swing.JLabel emailText;
    private javax.swing.JLabel feedbackMessage;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel localLabel;
    private javax.swing.JLabel localText;
    private javax.swing.JLabel moradaLabel;
    private javax.swing.JLabel moradaText;
    private javax.swing.JLabel nifText;
    private javax.swing.JLabel nomeText;
    private javax.swing.JLabel postalText;
    private javax.swing.JLabel telefoneText;
    // End of variables declaration//GEN-END:variables
}
