/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proj2ui;
import proj2.DAL.Utilizador;

/**
 *
 * @author nunop
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Criar
     */
    private MainFrame parentFrame = null;
     
    public Home(MainFrame parentFrame, Utilizador user) {
        initComponents();
        this.parentFrame = parentFrame;
       jLabel3.setText(user.getNome() + ", contamos com a sua ajuda para um bom desenvolvimento da nossa Cidade");
       this.parentFrame.getJMenuBar().setVisible(true);
           this.parentFrame.getJMenuBar().getMenu(0).setVisible(true);
           this.parentFrame.getJMenuBar().getMenu(1).setVisible(true);
           this.parentFrame.getJMenuBar().getMenu(2).setVisible(true);
           this.parentFrame.getJMenuBar().getMenu(3).setVisible(true);
           this.parentFrame.getJMenuBar().getMenu(4).setVisible(true);
           this.parentFrame.getJMenuBar().getMenu(5).setVisible(true);
       if (this.parentFrame != null && user.getTipoutil()==1){
           this.parentFrame.getJMenuBar().getMenu(1).setVisible(true);
           this.parentFrame.getJMenuBar().getMenu(2).setVisible(true);
           this.parentFrame.getJMenuBar().getMenu(3).setVisible(true);
           this.parentFrame.getJMenuBar().getMenu(4).setVisible(true);
           this.parentFrame.getJMenuBar().getMenu(5).setVisible(true);
           this.parentFrame.getJMenuBar().getMenu(0).setVisible(false);
       }else if(this.parentFrame != null && user.getTipoutil()==2){
           this.parentFrame.getJMenuBar().getMenu(0).setVisible(false);
           this.parentFrame.getJMenuBar().getMenu(2).setVisible(false);
           this.parentFrame.getJMenuBar().getMenu(4).setVisible(false);
           this.parentFrame.getJMenuBar().getMenu(5).setVisible(false);
       }
        
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        feedbackMessage = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(884, 525));
        setPreferredSize(new java.awt.Dimension(884, 525));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("A minha Viana");

        feedbackMessage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Bem-vindo à nossa Plataforma de Reclamações");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("do Município de Viana do Castelo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("contamos com a sua ajuda para um melhor funcionamento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(feedbackMessage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(256, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(256, 256, 256))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(384, 384, 384))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(305, 305, 305)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(150, 150, 150)
                .addComponent(feedbackMessage)
                .addGap(92, 92, 92))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel feedbackMessage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
